### ISSUE TITLE
This project appears abandoned

### ISSUE THREAD

**Issue by connorads** [antonbabenko/serverless.tf#4]
To the uninitiated it can appear that the `serverless.tf` project is abandoned.
1. There hasn't been any commits in 3 years so people might bounce because they assume it's abandoned
2. Is it worth updating the `README.md` to reflect any changes that have occurred in the past 3 years

**Comment by antonbabenko** [comment]
`serverless.tf` project is far from being abandoned, but this repository may falsely look so.

There was a lot of activity and commits in the [Terraform AWS modules](https://github.com/terraform-aws-modules) listed on [serverless.tf web-site](https://serverless.tf/#aws-serverless).

If you feel that you have something to add, please open a PR and I will be super glad to review it.
