### ISSUE TITLE
is it possible to add some kind of "Unified" Workflow for state management between the tools?

### ISSUE THREAD

**Issue by 99** [antonbabenko/serverless.tf#6]
Hi, is it possible and makes sense to add something like "Unified" Workflow for state management? 

Currently, managing Terraform state files and serverless deployments should be done separately. I could be wrong, but in some places where I work, this approach can lead to inconsistency, such as mismatched configurations, outdated references, etc.

Is there a way to ensure Terraform and Serverless deployments are managed together, reducing the chance of inconsistencies?  Some kind of way for Serverless.tf could automatically handle Terraform backend configuration and serverless deployment tracking?

Thank you.

**Comment by antonbabenko** [comment]
Thank you for asking this question - it gives me valuable information for improving this project!

There are multiple out-of-the-box ways to read properties of AWS resources created using different tools (e.g., Serverless Framework, AWS CloudFormation, Terraform, or manual ClickOps). The simplest one is to use data sources by tags/name.
Sharing such information Using Terraform's backend configuration can be possible, but it is often more complicated to set up and secure.
